
# AWG-NATIVE-BEGIN
location /proxy/network/awg-native/ {
    include /usr/share/unifi-core/http/cors.conf;
    include /usr/share/unifi-core/http/security.conf;
    include /usr/share/unifi-core/http/auth.conf;
    include /usr/share/unifi-core/http/proxy.conf;
    client_max_body_size 100k;
    proxy_read_timeout 90s;
    proxy_pass http://unix:/run/awg-native/api.sock:/;
}
location = /app-assets/network/react/js/94924.70c7742fc8b69f7ab986.js {
    include /usr/share/unifi-core/http/cors.conf;
    include /usr/share/unifi-core/http/security.conf;
    include /usr/share/unifi-core/http/auth.conf;
    include /usr/share/unifi-core/http/proxy.conf;
    alias /usr/lib/unifi/webapps/ROOT/app-unifi/react/js/94924.70c7742fc8b69f7ab986.js;
    expires off;
    add_header Cache-Control "no-store" always;
}
location = /app-assets/network/react/js/settings.c9b2a0ee0544312b21d4.js {
    include /usr/share/unifi-core/http/cors.conf;
    include /usr/share/unifi-core/http/security.conf;
    include /usr/share/unifi-core/http/auth.conf;
    include /usr/share/unifi-core/http/proxy.conf;
    alias /usr/lib/unifi/webapps/ROOT/app-unifi/react/js/settings.c9b2a0ee0544312b21d4.js;
    expires off;
    add_header Cache-Control "no-store" always;
}
location = /proxy/network/awg-native/refresh {
    include /usr/share/unifi-core/http/security.conf;
    include /usr/share/unifi-core/http/auth.conf;
    include /usr/share/unifi-core/http/proxy.conf;
    alias /data/awg-native/refresh.html;
    default_type text/html;
    add_header Cache-Control "no-store" always;
    add_header Clear-Site-Data '"cache"' always;
}
location = /awg-native-cache.js {
    include /usr/share/unifi-core/http/security.conf;
    alias /data/awg-native/cache-loader.js;
    default_type application/javascript;
    add_header Cache-Control "no-store" always;
}
# AWG-NATIVE-END
